#+TITLE: $\mathrm{\LaTeX}$ in VS Code
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS:  num:nil


* Introduction
  - Nowadays most mathematicians use $\mathrm{\LaTeX}$. Since it is quite a
    straightforward software to use, one may not think much about how to write
    $\mathrm{\LaTeX}$ more efficiently. In this course I will walk you through
    how to use $\mathrm{\LaTeX}$ in VS Code. This course is targeted for those
    who already know how to write $\mathrm{\LaTeX}$ but want to improve their
    efficiency. I'll teach you only the basics. I hope that after this
    course you can explore and enjoy more interesting and advanced techniques in
    your own.
* Lecture 1
  - We learn basics on VS Code and LaTeX Workshop.
  - [[./vscode_lecture1.html][Link to Lecture 1]]
* Lecture 2
  - We learn BibTeX and Vim. 
  - [[./vscode_lecture2.html][Link to Lecture 2]]
* Lecture 3
  - We learn Git and GitHub for version control and collaboration. 
  - [[./vscode_lecture3.html][Link to Lecture 3]]
