#+TITLE: Instructions for Professors


* Video instruction
- https://youtu.be/lywyNzUm7-o (in Korean)
- https://youtu.be/17v-8QSzKz8 (in English)
* How to login to Webwork
   1. Find your class here. https://webwork.skku.edu
   2. The course coordinator or the TA will send you your login id and password.
   3. Once you login, you can change the password by clicking =User Settings= in the sidebar.
   4. If you enter your email in =User Settings=, you will be able to receive questions from students through the system.
* Observing student progress
   1. Click =Student Progress=  under =Instructor Tools= in the side bar.
   2. You can check student progress by a homework set or by a student
* Viewing homework problems
   1. Click =Homework Sets= in the sidebar. It will show you homework sets and due dates.
   2. Click the homework set name that you want to view.
   3. You can see each problem by clicking the problem number.
   4. You can also download a pdf file of the homework problems by clicking the =Download PDF or TeX Hardcopy for Current Set= button.
* Homework dues
- Since the due dates of the homework sets are determined by the schedule, please cover the topics as scheduled in syllabus.
- The materials in each week must be covered by the end of the following week at the latest.
- If you are not able to do this, please ask the TA to change the due date.
* How to answer student's questions
- Your students can ask questions by clicking a button when they are working on a homework problem.
- When they do, you will receive an email that has a link to the problem.
- Clink on the link and it will ask you to log in to the webwork page.
- After logging in you can see the problem.
- You can then reply to the student by email.
- In most problems numbers are randomly generated. So what you see in a given
  problem is not exactly the same as what your students see.
  
